<? 
include_once(APPPATH.'/models/Entity.php');

class Cetakan extends Entity{ 

	var $query;

	function Cetakan()
	{
		$this->Entity(); 
	}

	function selectByParamsFIP1($paramsArray=array(),$limit=-1,$from=-1, $statement='')
	{
		$str = "
			SELECT
			AMBIL_PROPINSI ( B.PROPINSI_ID ) PROPINSI_SATKER,
			AMBIL_KABUPATEN ( B.PROPINSI_ID, B.KABUPATEN_ID ) KABUPATEN_SATKER,
			AMBIL_KECAMATAN ( B.PROPINSI_ID, B.KABUPATEN_ID, B.KECAMATAN_ID ) KECAMATAN_SATKER,
			AMBIL_KELURAHAN ( B.PROPINSI_ID, B.KABUPATEN_ID, B.KECAMATAN_ID, B.KELURAHAN_ID ) KELURAHAN_SATKER,
			B.ALAMAT ALAMAT_SATKER, B.TELEPON TELEPON_SATKER, B.KODEPOS KODEPOS_SATKER, B.NAMA NAMA_SATKER, FOTO,
			L.NAMA_PEGAWAI NAMA_ATASAN, L.NIP_PEGAWAI NIP_ATASAN, AMBIL_SATKER_INDUK ( A.SATKER_ID ) SATKER_INDUK,
			A.NIP_LAMA, A.NIP_BARU, A.NAMA, A.GELAR_DEPAN, A.GELAR_BELAKANG, TEMPAT_LAHIR, TANGGAL_LAHIR,
			CASE
				WHEN JENIS_KELAMIN = 'L' THEN 'Laki-laki' 
				WHEN JENIS_KELAMIN = 'P' THEN'Perempuan' 
			END JENIS_KELAMIN,
			( SELECT NAMA FROM AGAMA X WHERE X.AGAMA_ID = A.AGAMA_ID ) AGAMA,
			CASE
				WHEN A.STATUS_PEGAWAI = 1 THEN 'CPNS' 
				WHEN A.STATUS_PEGAWAI = 2 THEN 'PNS' 
				WHEN A.STATUS_PEGAWAI = 3 THEN 'Pensiun' 
				WHEN A.STATUS_PEGAWAI = 4 THEN 'Tewas' 
				WHEN A.STATUS_PEGAWAI = 5 THEN 'Wafat' 
				WHEN A.STATUS_PEGAWAI = 6 THEN 'Pindah' 
				WHEN A.STATUS_PEGAWAI = 7 THEN 'Parpol' 
			END STATUS_PEGAWAI,
			( SELECT NAMA FROM JENIS_PEGAWAI X WHERE X.JENIS_PEGAWAI_ID = A.JENIS_PEGAWAI_ID ) JENIS_PEGAWAI,
			( SELECT NAMA FROM KEDUDUKAN X WHERE X.KEDUDUKAN_ID = A.KEDUDUKAN_ID ) KEDUDUKAN,
			CASE	
				WHEN STATUS_KAWIN = 1 THEN 'Belum Kawin' 
				WHEN STATUS_KAWIN = 2 THEN 'Kawin' 
				WHEN STATUS_KAWIN = 3 THEN 'Janda' 
				WHEN STATUS_KAWIN = 4 THEN 'Duda' 
			END STATUS_KAWIN,
			SUKU_BANGSA, GOLONGAN_DARAH, A.ALAMAT, RT || '/' || RW RTRW,
			A.ALAMAT || ' RT.' || RT || ' ' || 'RW.' || RW ALAMATMODEL,
			AMBIL_KELURAHAN ( A.PROPINSI_ID, A.KABUPATEN_ID, A.KECAMATAN_ID, A.KELURAHAN_ID ) KELURAHAN,
			AMBIL_KECAMATAN ( A.PROPINSI_ID, A.KABUPATEN_ID, A.KECAMATAN_ID ) KECAMATAN,
			AMBIL_KABUPATEN ( A.PROPINSI_ID, A.KABUPATEN_ID ) KABUPATEN,
			AMBIL_PROPINSI ( A.PROPINSI_ID ) PROPINSI, A.KODEPOS, KARTU_PEGAWAI, ASKES, TASPEN, '' SUAMIISTRI,
			NPWP, NIK, C.NAMA NAMA_INSTANSI, C.JABATAN JABATAN_INSTANSI,
			C.MASA_KERJA_TAHUN || '-' || C.MASA_KERJA_BULAN MASA_KERJA_INSTANSI, D.TMT_CPNS TANGGAL_KERJA,
			D.NO_NOTA NOTA_CPNS, D.TANGGAL_NOTA TANGGAL_NOTA_CPNS,
			( SELECT JABATAN FROM PEJABAT_PENETAP X WHERE X.PEJABAT_PENETAP_ID = D.PEJABAT_PENETAP_ID 
				OR X.JABATAN = D.PEJABAT_PENETAP ) PEJABAT_PENETAP_CPNS,
			G.NO_SK NO_SK_CPNS, G.TANGGAL_SK TANGGAL_SK_CPNS, TMT_CPNS TMT_CPNS,
			( SELECT KODE FROM PANGKAT X WHERE X.PANGKAT_ID = D.PANGKAT_ID ) GOL_RUANG_CPNS,
			TANGGAL_TUGAS TANGGAL_TUGAS_CPNS, d.NO_STTPP, d.TANGGAL_STTPP TANGGAL_STTPP_CPNS,
			( SELECT JABATAN FROM PEJABAT_PENETAP X WHERE X.PEJABAT_PENETAP_ID = E.PEJABAT_PENETAP_ID 
				OR X.JABATAN = D.PEJABAT_PENETAP ) PEJABAT_PENETAP_PNS,
			E.NO_SK NO_SK_PNS, E.TANGGAL_SK TANGGAL_SK_PNS, TMT_PNS TMT_PNS,
			( SELECT KODE FROM PANGKAT X WHERE X.PANGKAT_ID = E.PANGKAT_ID ) GOL_RUANG_PNS,
			TANGGAL_SUMPAH TANGGAL_SUMPAH, F.STLUD, F.NO_STLUD, TANGGAL_STLUD TANGGAL_STLUD, F.NO_NOTA,
			F.TANGGAL_NOTA, F.KREDIT, f.pejabat_penetap, F.NO_SK SK_PANGKAT, F.TANGGAL_SK TANGGAL_SK_PANGKAT,
			F.TMT_PANGKAT TMT_PANGKAT, F.kode GOL_RUANG_PANGKAT,
			CASE	
				WHEN JENIS_KP = 1 THEN 'Reguler' 
				WHEN JENIS_KP = 2 THEN 'Pilihan (Struktural)' 
				WHEN JENIS_KP = 3 THEN 'Anumerta' 
				WHEN JENIS_KP = 4 THEN 'Pengabdian' 
				WHEN JENIS_KP = 5 THEN 'SK Lain-lain' 
				WHEN JENIS_KP = 6 THEN 'Pilihan (Fungsional)' 
			END JENIS_KP,
			F.MASA_KERJA_TAHUN || '-' || F.MASA_KERJA_BULAN MASA_KERJA_PANGKAT, F.MASA_KERJA_TAHUN,
			F.MASA_KERJA_BULAN, G.NO_SK NO_SK_KGB,G.TANGGAL_SK TANGGAL_SK_KGB,G.TMT_SK TMT_SK_KGB,
			G.MASA_KERJA_TAHUN || '-' || G.MASA_KERJA_BULAN GOL_RUANG_KGB,G.GAJI_POKOK,WILAYAH,
			KTUA, H.PENDIDIKAN,H.JURUSAN, H.NAMA_SEKOLAH, H.TEMPAT, I.NAMA NAMA_DIK_STRUK, J.NAMA NAMA_DIK_FUNGS,
			K.NAMA NAMA_DIK_TEKNIS,
			( SELECT NAMA FROM PENATARAN X WHERE X.PEGAWAI_ID = A.PEGAWAI_ID LIMIT 1 ) PENATARAN,
			( SELECT NAMA FROM SEMINAR X WHERE X.PEGAWAI_ID = A.PEGAWAI_ID LIMIT 1 ) SEMINAR,
			f.pejabat_penetap PENETAP_JABATAN, L.NO_SK NO_SK_JABATAN, L.TANGGAL_SK TANGGAL_SK_JABATAN, L.JABATAN,
			L.ESELON, L.TMT_ESELON TMT_ESELON, NO_PELANTIKAN, TANGGAL_PELANTIKAN TANGGAL_PELANTIKAN, A.FOTO_BLOB 
			FROM
			PEGAWAI A 
			LEFT JOIN SATKER B ON A.SATKER_ID = B.SATKER_ID
			LEFT JOIN PENGALAMAN_TERAKHIR C ON A.PEGAWAI_ID = C.PEGAWAI_ID
			LEFT JOIN SK_CPNS D ON A.PEGAWAI_ID = D.PEGAWAI_ID
			LEFT JOIN SK_PNS E ON A.PEGAWAI_ID = E.PEGAWAI_ID
			LEFT JOIN ( 
				SELECT * FROM pangkat_riwayat A LEFT JOIN pangkat B ON A.PANGKAT_ID = B.PANGKAT_ID 
			) F ON A.PANGKAT_RIWAYAT_ID = F.PANGKAT_RIWAYAT_ID
			LEFT JOIN GAJI_TERAKHIR G ON A.PEGAWAI_ID = G.PEGAWAI_ID
			LEFT JOIN PENDIDIKAN_TERAKHIR H ON A.PEGAWAI_ID = H.PEGAWAI_ID
			LEFT JOIN DIKLAT_STRUKTURAL_TERAKHIR I ON A.PEGAWAI_ID = I.PEGAWAI_ID
			LEFT JOIN DIKLAT_FUNGSIONAL_TERAKHIR J ON A.PEGAWAI_ID = J.PEGAWAI_ID
			LEFT JOIN DIKLAT_TEKNIS_TERAKHIR K ON A.PEGAWAI_ID = K.PEGAWAI_ID
			LEFT JOIN (
				SELECT C.nip_baru NAMA_PEGAWAI, C.nama NIP_PEGAWAI, A.NO_SK, A.TANGGAL_SK, A.nama JABATAN,
				b.nama ESELON, A.TMT_ESELON,A.JABATAN_RIWAYAT_ID,NO_PELANTIKAN, tanggal_pelantikan 
				FROM
				jabatan_riwayat
				A LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
				LEFT JOIN pegawai C ON A.pejabat_penetap_id = C.pegawai_id 
			) L ON A.JABATAN_RIWAYAT_ID = L.JABATAN_RIWAYAT_ID 
			WHERE
			1 = 1 
		";
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ";
		$this->query = $str;
		return $this->selectLimit($str,$limit,$from); 
    }

    function getCountByParamsSuamiIstriAnak($paramsArray=array(), $statement='')
	{
		$str = "SELECT COUNT(PEGAWAI_ID) AS ROWCOUNT FROM LIHATSUAMIISTRIANAK WHERE 1 = 1".$statement; 
	
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		$this->query = $str;
		// echo $str;exit;
		$this->select($str); 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0;  
    }

    function selectByParamsSuamiIstriAnak($paramsArray=array(),$limit=-1,$from=-1, $statement='')
	{
		$str = "SELECT * FROM LIHATSUAMIISTRIANAK WHERE 1 = 1 ".$statement; 
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ";
		$this->query = $str;
		return $this->selectLimit($str,$limit,$from); 
    }
} 
?>