<? 
include_once(APPPATH.'/models/Entity.php');

class Dyna extends Entity{ 

	var $query;

	function Dyna()
	{
		$this->Entity(); 
	}

	function selectmonitoring($paramsArray=array(),$limit=-1,$from=-1, $statement='', $orderby='')
	{
		$str = "
		SELECT
			/*A.PEGAWAI_ID, NIP_LAMA, A.FORMAT_NIP_BARU NIP_BARU, A.VNAMA_LENGKAP NAMA, A.TEMPAT_LAHIR
			, A.TANGGAL_LAHIR, A.JENIS_KELAMIN, A1.NAMA STATUS_PEGAWAI, B.GOL_RUANG, B.TMT_PANGKAT
			, C.ESELON, C.JABATAN, C.TMT_JABATAN, MP.NAMA JENIS_MAPEL, D.NAMA AGAMA
			, Z.JABATAN_TAMBAHAN_NAMA, Z.TMT_JABATAN_AKHIR, A.TELEPON, A.ALAMAT, E.NAMA SATKER
			, A.VTMT_PENSIUN TMT_PENSIUN, F.LULUS, F.PENDIDIKAN, A.SATKER_ID
			, G1.HUKUMAN_STATUS_TERAKHIR, SUBSTRING(C.ESELON_ID::TEXT, 1,1) STATUS_ESELON
			, A.TUGAS_TAMBAHAN_NEW*/
			AMBIL_UMUR(A.TANGGAL_LAHIR) UMUR_PEGAWAI
			, D.NAMA INFO_AGAMA, A1.NAMA INFO_STATUS_PEGAWAI, A2.NAMA INFO_TIPE_PEGAWAI
			, A3.NAMA INFO_JENIS_PEGAWAI, A4.NAMA INFO_KEDUDUKAN
			, B.GOL_RUANG_PANGKAT, B.TMT_PANGKAT, B.NO_SK_PANGKAT, B.TANGGAL_SK_PANGKAT
			, B.MASA_KERJA_PANGKAT, B.JABATAN_PENETAP_PANGKAT
			, A.*
		FROM
		(
			SELECT
			CASE STATUS_KAWIN
			WHEN 1 THEN 'Belum Kawin' WHEN 2 THEN 'Kawin' WHEN 3 THEN 'Janda'
			WHEN 4 THEN 'Duda' ELSE '' END INFO_STATUS_KAWIN
			, A.*
			FROM pegawai A
		) A
		LEFT JOIN status_pegawai A1 ON A1.STATUS_PEGAWAI_ID = A.STATUS_PEGAWAI
		LEFT JOIN tipe_pegawai A2 ON A2.TIPE_PEGAWAI_ID = A.TIPE_PEGAWAI_ID
		LEFT JOIN jenis_pegawai A3 ON A3.JENIS_PEGAWAI_ID = A.JENIS_PEGAWAI_ID
		LEFT JOIN kedudukan A4 ON A4.KEDUDUKAN_ID = A.KEDUDUKAN_ID
		LEFT JOIN
		(
			SELECT
				A.PANGKAT_RIWAYAT_ID, A.PANGKAT_ID, B.KODE GOL_RUANG_PANGKAT, A.TMT_PANGKAT
				, A.NO_SK NO_SK_PANGKAT, A.TANGGAL_SK TANGGAL_SK_PANGKAT
				, COALESCE(A.MASA_KERJA_TAHUN,0) || ' - ' || COALESCE(A.MASA_KERJA_BULAN,0) MASA_KERJA_PANGKAT
				, COALESCE(A.PEJABAT_PENETAP, PP.JABATAN) JABATAN_PENETAP_PANGKAT
			FROM pangkat_riwayat A
			LEFT JOIN pangkat B ON A.PANGKAT_ID = B.PANGKAT_ID
			LEFT JOIN pejabat_penetap PP ON PP.PEJABAT_PENETAP_ID = A.PEJABAT_PENETAP_ID
		) B ON A.PANGKAT_RIWAYAT_ID = B.PANGKAT_RIWAYAT_ID
		LEFT JOIN
		(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON, A.TMT_JABATAN, A.NAMA JABATAN
			FROM jabatan_riwayat A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
		) C ON A.JABATAN_RIWAYAT_ID = C.JABATAN_RIWAYAT_ID
		LEFT JOIN AGAMA D ON  A.AGAMA_ID = D.AGAMA_ID
		INNER JOIN SATKER E ON A.SATKER_ID = E.SATKER_ID
		LEFT JOIN
		(
			SELECT
			A.PENDIDIKAN_RIWAYAT_ID, TO_CHAR(A.TANGGAL_STTB, 'YYYY') LULUS, A1.NAMA PENDIDIKAN
			FROM pendidikan_riwayat A
			INNER JOIN PENDIDIKAN A1 ON A.PENDIDIKAN_ID = A1.PENDIDIKAN_ID
		) F ON A.PENDIDIKAN_RIWAYAT_ID = F.PENDIDIKAN_RIWAYAT_ID
		LEFT JOIN
		(
			SELECT
			A.HUKUMAN_ID, A.TANGGAL_MULAI, A.TANGGAL_AKHIR
			FROM hukuman A
		) G ON A.HUKUMAN_ID = G.HUKUMAN_ID
		LEFT JOIN
		(
			SELECT
			A.HUKUMAN_ID
			, CASE
			WHEN CURRENT_DATE >= TANGGAL_MULAI AND TANGGAL_AKHIR IS NULL THEN 1
			WHEN CURRENT_DATE <= TANGGAL_AKHIR AND CURRENT_DATE >= TANGGAL_MULAI THEN 1
			ELSE 0
			END HUKUMAN_STATUS_TERAKHIR
			FROM hukuman A
			WHERE TINGKAT_HUKUMAN_ID IN (2,3)
		) G1 ON A.HUKUMAN_ID = G1.HUKUMAN_ID
		LEFT JOIN jenis_mapel MP ON  MP.JENIS_MAPEL_ID = A.JENIS_MAPEL_ID
		LEFT JOIN
		(
			SELECT A.JABATAN_TAMBAHAN_ID, A.NAMA JABATAN_TAMBAHAN_NAMA, A.TMT_JABATAN TMT_JABATAN_AKHIR
			FROM jabatan_tambahan A
		) Z ON A.JABATAN_TAMBAHAN_ID = Z.JABATAN_TAMBAHAN_ID
		WHERE 1=1
		";
		
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		
		$str .= $statement." ".$orderby;
		$this->query = $str;
		// echo $str;exit;
				
		return $this->selectLimit($str,$limit,$from); 
    }

} 
?>