<? 
  
  include_once(APPPATH.'/models/Entity.php');

  class Rekap extends Entity{ 

	var $query;

    function Rekap()
	{
      $this->Entity(); 
    }


    function selectByParamsPegawaiBak($paramsArray=array(),$limit=-1,$from=-1, $statement='', $sOrder="")
	{
		$str = "
		SELECT
			A.PEGAWAI_ID, A.NIP_BARU,  
			A.NAMA,
			A.SATKER_NAMA,
			A.SATKER,  
			A.GOL_RUANG,
			A.ESELON,
			A. JABATAN
			, A.SATKER_INDUK_NAMA
			, A.TIPE_PEGAWAI_NAMA
			, A.STATUS_PEGAWAI_NAMA,TANGGAL_PENSIUN
			, A.STATUS_PEGAWAI
			, A.TIPE_PEGAWAI_NEW_ID
			, A.SATKER_ID
			, A.GOLONGAN_PPPK
		FROM
		(	
			SELECT A.PEGAWAI_ID, A.NIP_BARU,  
				A.NAMA,
				 ambil_satker_nama_dynamic(A.SATKER_ID) SATKER_NAMA,
				  A.SATKER,  
				B.GOL_RUANG,
				C.ESELON,
				COALESCE(C.JABATAN_FUNG, C.JABATAN_STRUK, C.JABATAN_PELAKSANA) JABATAN
				, AMBIL_SATKER_INDUK(A.SATKER_ID) SATKER_INDUK_NAMA
				, C.TIPE_PEGAWAI_NEW_ID
				, C.TIPE_PEGAWAI_NAMA
				, A.STATUS_PEGAWAI_NAMA
				,'01' || '-' || BULAN ||'-'|| COALESCE( NULLIF(BUP,NULL) , 0 ) + TAHUN TANGGAL_PENSIUN
				, STATUS_PEGAWAI
				, A.SATKER_ID
				, D.GOLONGAN_PPPK
				FROM
				(
					SELECT	
						A.STATUS_PEGAWAI,
						A.PEGAWAI_ID, NIP_BARU, 
						(CASE WHEN TRIM(COALESCE(GELAR_DEPAN, '')) = '' THEN '' ELSE TRIM(GELAR_DEPAN) || '. ' END) || A.NAMA || (CASE WHEN TRIM(COALESCE(GELAR_BELAKANG, '')) = '' THEN '' ELSE  ', ' || GELAR_BELAKANG END) NAMA, 
						A.TIPE_PEGAWAI_NEW_ID,
						 A.SATKER_ID,   E.NAMA SATKER
						,  SP.NAMA STATUS_PEGAWAI_NAMA,A.PANGKAT_RIWAYAT_ID,EXTRACT(DAY FROM TANGGAL_LAHIR) HARI,lpad(extract(month from TANGGAL_LAHIR + interval '1' month)::text, 2, '0') BULAN,EXTRACT(YEAR FROM TANGGAL_LAHIR) TAHUN
					FROM PEGAWAI A 
					LEFT JOIN STATUS_PEGAWAI SP ON A.STATUS_PEGAWAI = SP.STATUS_PEGAWAI_ID 
					INNER JOIN SATKER E ON A.SATKER_ID = E.SATKER_ID
				) A
				LEFT JOIN (SELECT A.PANGKAT_RIWAYAT_ID, A.PEGAWAI_ID, A.PANGKAT_ID, B.KODE GOL_RUANG,A.TMT_PANGKAT FROM PANGKAT_RIWAYAT A LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID) B ON A.PEGAWAI_ID = B.PEGAWAI_ID AND A.PANGKAT_RIWAYAT_ID = B.PANGKAT_RIWAYAT_ID
				LEFT JOIN 
				(	SELECT A.PEGAWAI_JABATAN_ID, A.PEGAWAI_ID, A.ESELON_ID, B.NAMA ESELON, C.NAMA JABATAN_FUNG,D.NAMA JABATAN_STRUK,E.NAMA JABATAN_PELAKSANA,G.TIPE_PEGAWAI_NEW_ID,G.NAMA TIPE_PEGAWAI_NAMA,A.BUP
					FROM PEGAWAI_JABATAN A 
					LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
					LEFT JOIN JABATAN_FUNGSIONAL_NEW C ON C.JABATAN_FUNGSIONAL_NEW_ID = A.JABATAN_FUNGSIONAL_NEW_ID
					LEFT JOIN JABATAN_STRUKTURAL_NEW D ON D.JABATAN_STRUKTURAL_NEW_ID = A.JABATAN_STRUKTURAL_NEW_ID
					LEFT JOIN JABATAN_PELAKSANA_NEW E ON E.JABATAN_PELAKSANA_NEW_ID = A.JABATAN_PELAKSANA_NEW_ID
					LEFT JOIN TIPE_PEGAWAI_NEW G ON G.TIPE_PEGAWAI_NEW_ID = A.TIPE_PEGAWAI_NEW_ID
					INNER JOIN 
					(
						SELECT A.PEGAWAI_ID, MAX (PEGAWAI_JABATAN_ID) PEGAWAI_JABATAN_ID
						FROM PEGAWAI_JABATAN A
						GROUP BY A.PEGAWAI_ID
					) F ON F.PEGAWAI_JABATAN_ID = A.PEGAWAI_JABATAN_ID
				) C ON A.PEGAWAI_ID = C.PEGAWAI_ID 
				LEFT JOIN 
				(	SELECT  A.PEGAWAI_ID,A.GOLONGAN_PPPK_ID,B.KODE GOLONGAN_PPPK
					FROM RIWAYAT_KONTRAK A
					LEFT JOIN GOLONGAN_PPPK B ON A.GOLONGAN_PPPK_ID = B.GOLONGAN_PPPK_ID
					INNER JOIN 
					(
						SELECT A.PEGAWAI_ID, MAX (RIWAYAT_KONTRAK_ID) RIWAYAT_KONTRAK_ID
						FROM RIWAYAT_KONTRAK A
						GROUP BY A.PEGAWAI_ID
					) F ON F.RIWAYAT_KONTRAK_ID = A.RIWAYAT_KONTRAK_ID
				) D ON A.PEGAWAI_ID = D.PEGAWAI_ID 
		) A
		WHERE 1=1 AND (STATUS_PEGAWAI = 1 OR STATUS_PEGAWAI = 2 OR STATUS_PEGAWAI = 4 OR STATUS_PEGAWAI = 5)

		"; 
		
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$sOrder;
		$this->query = $str;
				
		return $this->selectLimit($str,$limit,$from); 
    }
	
	 function selectByParamsPegawai($paramsArray=array(),$limit=-1,$from=-1, $statement='', $sOrder="")
	{
		$str = "
		SELECT
			A.PEGAWAI_ID, A.NIP_BARU,  
			A.NAMA,
			A.SATKER_NAMA,
			A.SATKER,  
			A.GOL_RUANG,
			A.ESELON,
			A. JABATAN
			, A.SATKER_INDUK_NAMA
			, A.TIPE_PEGAWAI_NAMA
			, A.STATUS_PEGAWAI_NAMA,TANGGAL_PENSIUN
			, A.STATUS_PEGAWAI
			, A.TIPE_PEGAWAI_NEW_ID
			, A.SATKER_ID
			, A.GOLONGAN_PPPK
		FROM
		(	
			SELECT A.PEGAWAI_ID, A.NIP_BARU,  
				A.NAMA,
				 ambil_satker_nama_dynamic(A.SATKER_ID) SATKER_NAMA,
				  A.SATKER,  
				B.GOL_RUANG,
				C.ESELON,
				COALESCE(C.JABATAN_FUNG, C.JABATAN_STRUK, C.JABATAN_PELAKSANA) JABATAN
				, AMBIL_SATKER_INDUK(A.SATKER_ID) SATKER_INDUK_NAMA
				, C.TIPE_PEGAWAI_NEW_ID
				, C.TIPE_PEGAWAI_NAMA
				, A.STATUS_PEGAWAI_NAMA
				, '01' || '-' || BULAN ||'-'|| COALESCE( NULLIF(BUP,NULL) , 0 ) + TAHUN TANGGAL_PENSIUN
				, STATUS_PEGAWAI
				, A.SATKER_ID
				, D.GOLONGAN_PPPK
				FROM
				(
					SELECT A.STATUS_PEGAWAI,
					A.PEGAWAI_ID, NIP_BARU, 
					NAMA
					, A.TIPE_PEGAWAI_NEW_ID
					, A.SATKER_ID,   A.NAMA SATKER
					, STATUS_PEGAWAI_NAMA
					, A.PANGKAT_RIWAYAT_ID
					, HARI
					, BULAN
					, CASE WHEN BULAN_CHECK = '12' THEN TAHUN_DEPAN
					ELSE TAHUN
					END TAHUN
					FROM
					(

						SELECT	
							A.STATUS_PEGAWAI,
							A.PEGAWAI_ID, NIP_BARU, 
							(CASE WHEN TRIM(COALESCE(GELAR_DEPAN, '')) = '' THEN '' ELSE TRIM(GELAR_DEPAN) || '. ' END) || A.NAMA || (CASE WHEN TRIM(COALESCE(GELAR_BELAKANG, '')) = '' THEN '' ELSE  ', ' || GELAR_BELAKANG END) NAMA, 
							A.TIPE_PEGAWAI_NEW_ID,
							 A.SATKER_ID,   E.NAMA SATKER
							,  SP.NAMA STATUS_PEGAWAI_NAMA,A.PANGKAT_RIWAYAT_ID
							,lpad(EXTRACT(DAY FROM TANGGAL_LAHIR)::text,2,'0') HARI
							,lpad(extract(month from TANGGAL_LAHIR + interval '1' month)::text, 2, '0') BULAN
							,EXTRACT(month from TANGGAL_LAHIR) BULAN_CHECK
							,EXTRACT(YEAR FROM TANGGAL_LAHIR) TAHUN
							,EXTRACT(YEAR FROM TANGGAL_LAHIR + interval '1' year) TAHUN_DEPAN
							,A.TANGGAL_LAHIR
						FROM PEGAWAI A 
						LEFT JOIN STATUS_PEGAWAI SP ON A.STATUS_PEGAWAI = SP.STATUS_PEGAWAI_ID 
						INNER JOIN SATKER E ON A.SATKER_ID = E.SATKER_ID
					) A
					
				) A
				LEFT JOIN (SELECT A.PANGKAT_RIWAYAT_ID, A.PEGAWAI_ID, A.PANGKAT_ID, B.KODE GOL_RUANG,A.TMT_PANGKAT FROM PANGKAT_RIWAYAT A LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID) B ON A.PEGAWAI_ID = B.PEGAWAI_ID AND A.PANGKAT_RIWAYAT_ID = B.PANGKAT_RIWAYAT_ID
				LEFT JOIN 
				(	SELECT A.PEGAWAI_JABATAN_ID, A.PEGAWAI_ID, A.ESELON_ID, B.NAMA ESELON, C.NAMA JABATAN_FUNG,D.NAMA JABATAN_STRUK,E.NAMA JABATAN_PELAKSANA,G.TIPE_PEGAWAI_NEW_ID,G.NAMA TIPE_PEGAWAI_NAMA,A.BUP
					FROM PEGAWAI_JABATAN A 
					LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
					LEFT JOIN JABATAN_FUNGSIONAL_NEW C ON C.JABATAN_FUNGSIONAL_NEW_ID = A.JABATAN_FUNGSIONAL_NEW_ID
					LEFT JOIN JABATAN_STRUKTURAL_NEW D ON D.JABATAN_STRUKTURAL_NEW_ID = A.JABATAN_STRUKTURAL_NEW_ID
					LEFT JOIN JABATAN_PELAKSANA_NEW E ON E.JABATAN_PELAKSANA_NEW_ID = A.JABATAN_PELAKSANA_NEW_ID
					LEFT JOIN TIPE_PEGAWAI_NEW G ON G.TIPE_PEGAWAI_NEW_ID = A.TIPE_PEGAWAI_NEW_ID
					INNER JOIN 
					(
						SELECT A.PEGAWAI_ID, MAX (PEGAWAI_JABATAN_ID) PEGAWAI_JABATAN_ID
						FROM PEGAWAI_JABATAN A
						GROUP BY A.PEGAWAI_ID
					) F ON F.PEGAWAI_JABATAN_ID = A.PEGAWAI_JABATAN_ID
				) C ON A.PEGAWAI_ID = C.PEGAWAI_ID 
				LEFT JOIN 
				(	SELECT  A.PEGAWAI_ID,A.GOLONGAN_PPPK_ID,B.KODE GOLONGAN_PPPK
					FROM RIWAYAT_KONTRAK A
					LEFT JOIN GOLONGAN_PPPK B ON A.GOLONGAN_PPPK_ID = B.GOLONGAN_PPPK_ID
					INNER JOIN 
					(
						SELECT A.PEGAWAI_ID, MAX (RIWAYAT_KONTRAK_ID) RIWAYAT_KONTRAK_ID
						FROM RIWAYAT_KONTRAK A
						GROUP BY A.PEGAWAI_ID
					) F ON F.RIWAYAT_KONTRAK_ID = A.RIWAYAT_KONTRAK_ID
				) D ON A.PEGAWAI_ID = D.PEGAWAI_ID 
		) A
		WHERE 1=1 AND (STATUS_PEGAWAI = 1 OR STATUS_PEGAWAI = 2 OR STATUS_PEGAWAI = 4 OR STATUS_PEGAWAI = 5)

		"; 
		
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$sOrder;
		$this->query = $str;
				
		return $this->selectLimit($str,$limit,$from); 
    }

    function selectByParamsTipePegawai($paramsArray=array(),$limit=-1,$from=-1, $statement='', $sOrder="")
	{
		$str = "
		SELECT * FROM TIPE_PEGAWAI_NEW
		WHERE 1=1
		"; 
		
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$sOrder;
		$this->query = $str;
				
		return $this->selectLimit($str,$limit,$from); 
    }
    
        
  } 
?>