<? 
  include_once(APPPATH.'/models/Entity.php');

  class Validasi extends Entity{ 

    var $query;
    function Validasi()
    {
      $this->Entity(); 
    }

    function selectByParamsMonitoring($paramsArray=array(),$limit=-1,$from=-1, $statement='', $sOrder="ORDER BY A.PEGAWAI_ID, A.FORM_FIP ASC")
  {
    $str= "
   SELECT
    A.PEGAWAI_ID, A.SATKER_ID, A.VALIDASI, CASE WHEN A.VALIDASI = 0 THEN 'DITOLAK' WHEN A.VALIDASI = 1 THEN 'VALIDASI' ELSE 'BELUM VALIDASI' END VALIDASI_INFO, A.NIP_BARU_VIEW, A.GROUP_NAMA, 
    A.SATKER, A.FORM_FIP, A.TIPE_PERUBAHAN_DATA, A.TANGGAL_PROSES, A.TANGGAL_VALIDASI,A.LINK_FORM,A.ROW_ID,TEMP_VALIDASI_ID
    FROM
    (
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 02, Anak' FORM_FIP,
      CASE WHEN  A.ANAK_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_anak_add' LINK_FORM,A.ANAK_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.ANAK A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
      UNION ALL
      SELECT B.PEGAWAI_ID, C.SATKER_ID, A.VALIDASI,
      C.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(C.NIP_BARU),'') || ' - ' || C.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(C.SATKER_ID) SATKER,
      'FIP - 02, Anak' FORM_FIP,
      'HAPUS DATA' TIPE_PERUBAHAN_DATA,
      A.LAST_CREATE_DATE TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_anak_add' LINK_FORM,B.ANAK_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.HAPUS_DATA A
      INNER JOIN ANAK B ON A.TEMP_VALIDASI_ID = B.ANAK_ID
      INNER JOIN PEGAWAI C ON C.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE A.HAPUS_NAMA = 'ANAK'
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 02, Penguasaan Bahasa' FORM_FIP,
      CASE WHEN  A.BAHASA_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_bahasa_add' LINK_FORM,A.BAHASA_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.BAHASA A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
      UNION ALL
      SELECT B.PEGAWAI_ID, C.SATKER_ID, A.VALIDASI,
      C.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(C.NIP_BARU),'') || ' - ' || C.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(C.SATKER_ID) SATKER,
      'FIP - 02, Penguasaan Bahasa' FORM_FIP,
      'HAPUS DATA' TIPE_PERUBAHAN_DATA,
      A.LAST_CREATE_DATE TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_bahasa_add' LINK_FORM,B.BAHASA_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.HAPUS_DATA A
      INNER JOIN BAHASA B ON A.TEMP_VALIDASI_ID = B.BAHASA_ID
      INNER JOIN PEGAWAI C ON C.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE A.HAPUS_NAMA = 'BAHASA'
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 02, Cuti' FORM_FIP,
      CASE WHEN  A.CUTI_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_cuti_add' LINK_FORM,A.CUTI_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.CUTI A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
      UNION ALL
      SELECT B.PEGAWAI_ID, C.SATKER_ID, A.VALIDASI,
      C.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(C.NIP_BARU),'') || ' - ' || C.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(C.SATKER_ID) SATKER,
      'FIP - 02, Cuti' FORM_FIP,
      'HAPUS DATA' TIPE_PERUBAHAN_DATA,
      A.LAST_CREATE_DATE TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_cuti_add' LINK_FORM,B.CUTI_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.HAPUS_DATA A
      INNER JOIN CUTI B ON A.TEMP_VALIDASI_ID = B.CUTI_ID
      INNER JOIN PEGAWAI C ON C.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE A.HAPUS_NAMA = 'CUTI'     
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 02, Hukuman' FORM_FIP,
      CASE WHEN  A.HUKUMAN_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_hukuman_add' LINK_FORM,A.HUKUMAN_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.HUKUMAN A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
      UNION ALL
      SELECT B.PEGAWAI_ID, C.SATKER_ID, A.VALIDASI,
      C.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(C.NIP_BARU),'') || ' - ' || C.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(C.SATKER_ID) SATKER,
      'FIP - 02, Hukuman' FORM_FIP,
      'HAPUS DATA' TIPE_PERUBAHAN_DATA,
      A.LAST_CREATE_DATE TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_hukuman_add' LINK_FORM,B.HUKUMAN_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.HAPUS_DATA A
      INNER JOIN HUKUMAN B ON A.TEMP_VALIDASI_ID = B.HUKUMAN_ID
      INNER JOIN PEGAWAI C ON C.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE A.HAPUS_NAMA = 'HUKUMAN'
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 02, Kursus' FORM_FIP,
      CASE WHEN  A.KURSUS_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_kursus_add' LINK_FORM,A.KURSUS_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.KURSUS A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
      UNION ALL
      SELECT B.PEGAWAI_ID, C.SATKER_ID, A.VALIDASI,
      C.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(C.NIP_BARU),'') || ' - ' || C.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(C.SATKER_ID) SATKER,
      'FIP - 02, Kursus' FORM_FIP,
      'HAPUS DATA' TIPE_PERUBAHAN_DATA,
      A.LAST_CREATE_DATE TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_kursus_add' LINK_FORM,B.KURSUS_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.HAPUS_DATA A
      INNER JOIN KURSUS B ON A.TEMP_VALIDASI_ID = B.KURSUS_ID
      INNER JOIN PEGAWAI C ON C.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE A.HAPUS_NAMA = 'KURSUS'
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 02, Organisasi' FORM_FIP,
      CASE WHEN  A.ORGANISASI_RIWAYAT_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_organisasi_add' LINK_FORM,A.ORGANISASI_RIWAYAT_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.ORGANISASI_RIWAYAT A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
    UNION ALL
      SELECT B.PEGAWAI_ID, C.SATKER_ID, A.VALIDASI,
      C.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(C.NIP_BARU),'') || ' - ' || C.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(C.SATKER_ID) SATKER,
      'FIP - 02, Organisasi' FORM_FIP,
      'HAPUS DATA' TIPE_PERUBAHAN_DATA,
      A.LAST_CREATE_DATE TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_organisasi_add' LINK_FORM,B.ORGANISASI_RIWAYAT_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.HAPUS_DATA A
      INNER JOIN ORGANISASI_RIWAYAT B ON A.TEMP_VALIDASI_ID = B.ORGANISASI_RIWAYAT_ID
      INNER JOIN PEGAWAI C ON C.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE A.HAPUS_NAMA = 'ORGANISASI_RIWAYAT'
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 02, Penghargaan' FORM_FIP,
      CASE WHEN  A.PENGHARGAAN_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_penghargaan_add' LINK_FORM,A.PENGHARGAAN_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.PENGHARGAAN A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
    UNION ALL
      SELECT B.PEGAWAI_ID, C.SATKER_ID, A.VALIDASI,
      C.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(C.NIP_BARU),'') || ' - ' || C.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(C.SATKER_ID) SATKER,
      'FIP - 02, Penghargaan' FORM_FIP,
      'HAPUS DATA' TIPE_PERUBAHAN_DATA,
      A.LAST_CREATE_DATE TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_penghargaan_add' LINK_FORM,B.PENGHARGAAN_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.HAPUS_DATA A
      INNER JOIN PENGHARGAAN B ON A.TEMP_VALIDASI_ID = B.PENGHARGAAN_ID
      INNER JOIN PEGAWAI C ON C.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE A.HAPUS_NAMA = 'PENGHARGAAN'
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 02, Penilaian Potensi Diri' FORM_FIP,
      CASE WHEN  A.POTENSI_DIRI_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_penilaian_potensi_add' LINK_FORM,A.POTENSI_DIRI_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.POTENSI_DIRI A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
    UNION ALL
      SELECT B.PEGAWAI_ID, C.SATKER_ID, A.VALIDASI,
      C.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(C.NIP_BARU),'') || ' - ' || C.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(C.SATKER_ID) SATKER,
      'FIP - 02, Penilaian Potensi Diri' FORM_FIP,
      'HAPUS DATA' TIPE_PERUBAHAN_DATA,
      A.LAST_CREATE_DATE TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_penilaian_potensi_add' LINK_FORM,B.POTENSI_DIRI_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.HAPUS_DATA A
      INNER JOIN POTENSI_DIRI B ON A.TEMP_VALIDASI_ID = B.POTENSI_DIRI_ID
      INNER JOIN PEGAWAI C ON C.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE A.HAPUS_NAMA = 'POTENSI_DIRI'
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'Lain-lain, Penilaian Prestasi Kerja (SKP)' FORM_FIP,
      CASE WHEN  A.PENILAIAN_KERJA_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_penilaian_prestasi_add' LINK_FORM,A.PENILAIAN_KERJA_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.PENILAIAN_KERJA A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
      UNION ALL
      SELECT B.PEGAWAI_ID, C.SATKER_ID, A.VALIDASI,
      C.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(C.NIP_BARU),'') || ' - ' || C.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(C.SATKER_ID) SATKER,
      'Lain-lain, Penilaian Prestasi Kerja (SKP)' FORM_FIP,
      'HAPUS DATA' TIPE_PERUBAHAN_DATA,
      A.LAST_CREATE_DATE TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_penilaian_prestasi_add' LINK_FORM,B.PENILAIAN_KERJA_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.HAPUS_DATA A
      INNER JOIN PENILAIAN_KERJA B ON A.TEMP_VALIDASI_ID = B.PENILAIAN_KERJA_ID
      INNER JOIN PEGAWAI C ON C.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE A.HAPUS_NAMA = 'PENILAIAN_KERJA'
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 02, Tambahkan Masa Kerja' FORM_FIP,
      CASE WHEN  A.TAMBAHAN_MASA_KERJA_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/tambahan_masa_kerja' LINK_FORM,A.TAMBAHAN_MASA_KERJA_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.TAMBAHAN_MASA_KERJA A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 02, Suami Istri' FORM_FIP,
      CASE WHEN  A.SUAMI_ISTRI_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_suami_istri_add' LINK_FORM,A.SUAMI_ISTRI_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.SUAMI_ISTRI A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
      AND CASE WHEN A.SUAMI_ISTRI_ID IS NULL THEN 1 ELSE (SELECT 1 FROM SUAMI_ISTRI X WHERE X.SUAMI_ISTRI_ID = A.SUAMI_ISTRI_ID) END = 1
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 02, Orang Tua Laki - Laki' FORM_FIP,
      CASE WHEN  A.ORANG_TUA_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_orang_tua' LINK_FORM,A.ORANG_TUA_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.ORANG_TUA A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1 AND A.JENIS_KELAMIN = 'L'
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 02, Orang Tua Perempuan' FORM_FIP,
      CASE WHEN  A.ORANG_TUA_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_orang_tua' LINK_FORM,A.ORANG_TUA_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.ORANG_TUA A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1 AND A.JENIS_KELAMIN = 'P'
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP , Diklat' FORM_FIP,
      CASE WHEN  A.PEGAWAI_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_diklat_add' LINK_FORM,A.PEGAWAI_DIKLAT_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.PEGAWAI_DIKLAT A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
    UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 01, Identitas Pegawai' FORM_FIP,
      CASE WHEN  A.PEGAWAI_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_data' LINK_FORM,A.PEGAWAI_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.PEGAWAI A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
   UNION ALL
      SELECT A.PEGAWAI_ID, B.SATKER_ID, A.VALIDASI,
      B.NIP_BARU NIP_BARU_VIEW,
      COALESCE(AMBIL_FORMAT_NIP_BARU(B.NIP_BARU),'') || ' - ' || B.NAMA GROUP_NAMA,
      AMBIL_SATKER_NAMA(B.SATKER_ID) SATKER,
      'FIP - 02, Jabatan' FORM_FIP,
      CASE WHEN  A.PEGAWAI_ID IS NULL THEN 'TAMBAH DATA' ELSE 'UBAH DATA' END TIPE_PERUBAHAN_DATA,
      COALESCE(A.LAST_UPDATE_DATE, A.LAST_CREATE_DATE) TANGGAL_PROSES, 
      A.TANGGAL_VALIDASI,
      'app/index/pegawai_jabatan_tipe_add' LINK_FORM,A.PEGAWAI_ID ROW_ID,TEMP_VALIDASI_ID
      FROM VALIDASI.PEGAWAI_JABATAN A
      INNER JOIN PEGAWAI B ON A.PEGAWAI_ID = B.PEGAWAI_ID
      WHERE 1=1
    ) A
    WHERE 1=1
    --AND ROW_ID IS NULL 
    "; 
    
    while(list($key,$val) = each($paramsArray))
    {
      $str .= " AND $key = '$val' ";
    }
    
    $str .= $statement." ".$sOrder;
    $this->query = $str;
        
    return $this->selectLimit($str,$limit,$from); 
    }

  } 
?>